### ISSUE TITLE
No API log is available in logcat

### ISSUE THREAD

**Issue by lowdog005** [MindMac/AndroidEagleEye#1]
Hello,

I am searching instrumentation solutions for Android apps, and happen to see your project. I had some experiment. However, no log relevant to EagleEye is shown in the logcat.

My device is a Samsung GS4, I installed Xposed 2.6.1 on it, EagleEye module is also enabled.

The properties are also set, as can be seen in the following command result:

root@android:/ # ps |grep eagle  
u0_a249   7321  219   901924 74188 ffffffff 40329004 S com.mindmac.eagleeyetest
u0_a248   7540  219   873920 47048 ffffffff 40329004 S com.mindmac.eagleeye

root@android:/ # getprop | grep eag  
rw.eagleeye.fr.uids:  10248|10249
rw.eagleeye.n1t.uids: 10248|10249

Do you know what might be the problem? Or how to debug?

Since I am quite new to this area, can you recommend any practical and stable solution to profile/trace app behaviors. Thanks,

Luke

**Comment by MindMac** [comment]
You need to restart the target application. You can remove the application from the recent apps or use command to kill the related processes, and launch it again.
