### ISSUE TITLE
Why it cannot work on my phone?

### ISSUE THREAD

**Issue by halo2me** [MindMac/AndroidEagleEye#3]
Nexus 6 and Android 5.1.1
First, I download the zip, and install the EagleEye.apk and EagleEyeTest.apk on my phone,  i followed step but when i restart EagleEyeTest, the log print like this:
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_open
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_socket
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_connect
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_bind
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_listen
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_accept
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_read
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_write
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_sendto
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_recvfrom
12-07 15:40:55.749: D/EagleEye(26426): hook info node: system_hook_info_execve
12-07 15:40:55.749: D/EagleEye(26426): Try to hook open in lib libc
12-07 15:40:55.760: D/EagleEye(26426): cannot find function: open
12-07 15:40:55.760: D/EagleEye(26426): can't find: open
12-07 15:40:55.760: D/EagleEye(26426): Try to hook socket in lib libc
12-07 15:40:55.776: D/EagleEye(26426): cannot find function: socket
12-07 15:40:55.776: D/EagleEye(26426): can't find: socket
12-07 15:40:55.776: D/EagleEye(26426): Try to hook connect in lib libc
12-07 15:40:55.789: D/EagleEye(26426): cannot find function: connect
12-07 15:40:55.789: D/EagleEye(26426): can't find: connect
12-07 15:40:55.789: D/EagleEye(26426): Try to hook bind in lib libc
12-07 15:40:55.798: D/EagleEye(26426): cannot find function: bind
12-07 15:40:55.798: D/EagleEye(26426): can't find: bind
12-07 15:40:55.798: D/EagleEye(26426): Try to hook listen in lib libc
12-07 15:40:55.807: D/EagleEye(26426): cannot find function: listen
12-07 15:40:55.807: D/EagleEye(26426): can't find: listen
12-07 15:40:55.807: D/EagleEye(26426): Try to hook accept in lib libc
12-07 15:40:55.815: D/EagleEye(26426): cannot find function: accept
12-07 15:40:55.815: D/EagleEye(26426): Try to hook read in lib libc
12-07 15:40:55.825: D/EagleEye(26426): cannot find function: read
12-07 15:40:55.825: D/EagleEye(26426): can't find: read
12-07 15:40:55.825: D/EagleEye(26426): Try to hook write in lib libc
12-07 15:40:55.836: D/EagleEye(26426): cannot find function: write
12-07 15:40:55.836: D/EagleEye(26426): can't find: write
12-07 15:40:55.836: D/EagleEye(26426): Try to hook sendto in lib libc
12-07 15:40:55.845: D/EagleEye(26426): cannot find function: sendto
12-07 15:40:55.845: D/EagleEye(26426): can't find: sendto
12-07 15:40:55.845: D/EagleEye(26426): Try to hook recvfrom in lib libc
12-07 15:40:55.856: D/EagleEye(26426): cannot find function: recvfrom
12-07 15:40:55.856: D/EagleEye(26426): can't find: recvfrom
12-07 15:40:55.856: D/EagleEye(26426): Try to hook execve in lib libc
12-07 15:40:55.872: D/EagleEye(26426): cannot find function: execve
12-07 15:40:55.872: D/EagleEye(26426): can't find: execve
so ,can you fix it?

**Comment by MindMac** [comment]
It seems that adbi cannot work properly on Android 5.1.1 system.
