### ISSUE TITLE
when i use ndk-build build my "libeagleeyenative.so"

### ISSUE THREAD

**Issue by DrizzleRisk** [MindMac/AndroidEagleEye#5]
I use ndk-build build my "libeagleeyenative.so", but it doesn't work on my phone .
i just replace my libeagleeyenative.so in original edition EagleEye.apk ,and signed it ,is there some problems?

**Comment by MindMac** [comment]
Does the original one work? Any logs?

**Comment by DrizzleRisk** [comment]
@MindMac The original one worked.
Is it possible because the x86 and arm?(my virtual machine is x86)
err log:

## ![image](https://cloud.githubusercontent.com/assets/6161410/15207415/aec30b8e-1858-11e6-9794-a54987ead6c6.png)

Maybe not ?

when i use the original libeagleeyenative.so:
![image](https://cloud.githubusercontent.com/assets/6161410/15202029/248ade80-1829-11e6-91ba-37a9423d7596.png)

I use ndk-build build my "libeagleeyenative.so":

![image](https://cloud.githubusercontent.com/assets/6161410/15202024/178f4b08-1829-11e6-8e4d-d0ffea510b9e.png)

And then i replace the .so in apk (with apktool rebuild, and singned it)

when i use mine(it doesn't work):
![image](https://cloud.githubusercontent.com/assets/6161410/15201960/a64c5c24-1828-11e6-9aa3-6a8813b27e03.png)

I was confused

what's your ndk version ?

**Comment by MindMac** [comment]
I didn't test on x86 machine. Can you try this? http://stackoverflow.com/a/34509138/1656256

**Comment by DrizzleRisk** [comment]
@MindMac Are u Chinese ?
I have tried this, it doesn't work(can't build ,seems adbi doesn't supports x86)
but I was confused that why the original  libeagleeyenative.so can run in x86 but my libeagleeyenative.so can not ??

**Comment by MindMac** [comment]
@DrizzleRisk yes
no idea either, can u try to compile the whole project to generate an APK instead of repackaging it?

**Comment by DrizzleRisk** [comment]
@MindMac 
Today , I tried AndroidEagleEye on my  **arm** based Android phone ,also doesn't work .
Err Log says: "cannot locate symbol tcgetarry"

![image](https://cloud.githubusercontent.com/assets/6161410/15237452/816e6144-1900-11e6-82c6-b216eb06568e.png)

---

**What's your ndk version ?** Mine is r10. CAN I get your QQ or Wechat ?Thx , I am Chinese .

**Comment by MindMac** [comment]
@DrizzleRisk 邮件联系 mindmac.hu#gmail.com

**Comment by DrizzleRisk** [comment]
我换了个NDK版本就OK了，关闭问题吧，多谢~！
